### ISSUE TITLE
Wallpaper not changing: Output of "echo $DESKTOP_SESSION" is "zorin"

### ISSUE THREAD

**Issue by Michael-Obele** [adi1090x/dynamic-wallpaper#84]
![image](https://user-images.githubusercontent.com/70345027/144947209-2f80155b-ed5a-4e6a-978e-2fefe2791db9.png)

**Comment by Michael-Obele** [comment]
PS: Am using Zorin OS 16

**Comment by histefanhere** [comment]
I'm also using zorin, and it turns out it's a super easy fix to get it working!

Basically zorin has it's own desktop session, however it's still based on ubuntu gnome which this should support. I followed ChocolateDave's steps in @96 [here](https://github.com/adi1090x/dynamic-wallpaper/issues/96#issuecomment-1193296687) by changing the folowing line in `/usr/bin/dwall`:

```
elif [[ "$DESKTOP_SESSION" =~ ^(PANTHEON|zorin|Pantheon|pantheon|GNOME|Gnome|gnome|Gnome-xorg|gnome-xorg|UBUNTU|Ubuntu|ubuntu|DEEPIN|Deepin|deepin|POP|Pop|pop)$ ]]; then
	SETTER="gsettings set org.gnome.desktop.background picture-uri"
```

simply add `zorin|` anywhere into the pattern as I have which tells dwall how to handle changing the wallpaper in zorin, and after this it should work! Enjoy :)

**Comment by Michael-Obele** [comment]
Thank you very much. This is excellent. As far as I can see, this also applies to other 'wallpaper shell apps'. Once again, thank you.
